### ISSUE TITLE
Checking out the project

### ISSUE THREAD

**Issue by Pysis868** [leyed0/PFS_HDD_Manager_VS#1]
Looks neat.  Couldn't find much to do with it yet rather than maybe view some files, but I didn't have a local PFS/PS2-formatted hard drive connected directly/locally to my computer to test that out.  I was looking for more functionality, but I might just get that from the PS2 software/homebrew directly on the console using the system calls available if I don't like running many executables on my PC.

If the project grows I would recommend adding language files / external strings.

I could not get it with the sln file properly recognized in VSCode, even with the specific plugin for it `vscode-solution-explorer`.  I saw it is a VS15 project.  I went ahead and opened it in the somewhat latest VS2017 Community edition and it seemed to work well enough :).

**Comment by leyed0** [comment]
It`s just the project skelleton yet.
I am developping the libraries to get and manage the ps2 filesystem... It will take some time. The project is just starting and needs a lot of codding before being really able to do anything cool.

If you connect a ps2-formatted HDD and press the debug button you will get it`s partition table and that`s it... For now

Things i`m doing now: 
- Libraries to manage PfsShell output
- Libraries to manage ps2 folder and partition structure
- a simple read-me file, with instructions to compile it in VS2017
- thinking about the language files (maybe a xml archive)

**Comment by TheGrey01** [comment]
Is this project dead?

**Comment by leyed0** [comment]
on hold. I will make a better version

**Comment by leyed0** [comment]
i`m studing to make it multiplatform

**Comment by Pysis868** [comment]
Any ideas on that?  Seems like a C* project, and with that GUI frameworks like Qt/GTK and any others if I'm forgetting.

Otherwise I usually try to make projects with script files and CLI utils, or JS/Python.  Python does have tkinter to use for a GUI, although my preference is web-based with plain HTML5, maybe even using Electron too.

How are the libs doing?

**Comment by leyed0** [comment]
So... First problem is that I am trying to get the sourcecode from pfsshell and compile it manually in a way that i can acess its functions directly from the GUI using C++...
This version of the program is running pfsshell in the background every time theres a change... An it makes the program very limited and hard to manage.
Before i start the multiplatform work this have to be working...
second, I am planning on using wxwidgets for the gui... But its a thing that i didn't really gave attention right now.... I could change this on any moment

**Comment by leyed0** [comment]
after the pfsshell code ir working i am thinking in using html and a webview to form a good looking file explorer... But its not the focus right now
